version: '2'
services:
    app:
        image: linux/app
        build: ./app/       
    proxy:
        image: linux/nginx
        build: ./nginx/
        ports:            
            - "5000:80"     
        depends_on: 
            - app