version: '3.3'
services:
    app:
        image: swarm/app
        build: ./app/  
        networks:
            - mynetwork
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
    proxy:
        image: swarm/nginx
        build: ./nginx/
        ports:            
            - "5000:80"     
        depends_on: 
            - app
        networks:
            - mynetwork
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
networks: 
    mynetwork: