version: '3.3'
services:
    app:
        image: windows/app
        restart: unless-stopped
        build: ./app/
    proxy:
        image: windows/nginx
        restart: unless-stopped
        build: ./nginx/
        ports:            
            - "5000:80"